import { expect, test } from "bun:test"
import type { AnyCircuitElement } from "circuit-json"
import { runSolverAndRenderToSvg } from "./utils/run-solver-and-render-to-svg"

const circuitJson = [
  {
    type: "pcb_board",
    pcb_board_id: "pcb_board_0",
    center: { x: 0, y: 0 },
    width: 10,
    height: 7,
    thickness: 1.4,
    num_layers: 2,
    material: "fr4",
  },
  {
    type: "source_net",
    source_net_id: "source_net_gnd",
    name: "GND",
    subcircuit_connectivity_map_key: "parent_gnd_key",
  },
  {
    type: "source_trace",
    source_trace_id: "source_trace_parent_gnd",
    connected_source_net_ids: ["source_net_gnd"],
    connected_source_port_ids: ["source_port_parent_gnd"],
    subcircuit_connectivity_map_key: "parent_gnd_key",
  },
  {
    type: "source_trace",
    source_trace_id: "source_trace_passive_gnd",
    connected_source_net_ids: ["source_net_gnd"],
    connected_source_port_ids: ["source_port_passive_gnd"],
    subcircuit_connectivity_map_key: "passive_gnd_key",
  },
  {
    type: "source_component",
    source_component_id: "source_component_parent_connector",
    ftype: "simple_pin_header",
    name: "J1",
  },
  {
    type: "source_component",
    source_component_id: "source_component_passive",
    ftype: "simple_resistor",
    name: "R1",
    resistance: 10000,
    display_resistance: "10k",
    are_pins_interchangeable: true,
  },
  {
    type: "source_port",
    source_port_id: "source_port_parent_gnd",
    source_component_id: "source_component_parent_connector",
    name: "GND",
    pin_number: 1,
    port_hints: ["GND", "1"],
    subcircuit_connectivity_map_key: "parent_gnd_key",
  },
  {
    type: "source_port",
    source_port_id: "source_port_passive_signal",
    source_component_id: "source_component_passive",
    name: "pin1",
    pin_number: 1,
    port_hints: ["pin1", "left", "1"],
  },
  {
    type: "source_port",
    source_port_id: "source_port_passive_gnd",
    source_component_id: "source_component_passive",
    name: "pin2",
    pin_number: 2,
    port_hints: ["pin2", "right", "2"],
    subcircuit_connectivity_map_key: "passive_gnd_key",
  },
  {
    type: "pcb_component",
    pcb_component_id: "pcb_component_parent_connector",
    source_component_id: "source_component_parent_connector",
    center: { x: -3, y: 0 },
    width: 1.4,
    height: 1.4,
    layer: "top",
    rotation: 0,
    do_not_place: false,
    obstructs_within_bounds: true,
  },
  {
    type: "pcb_component",
    pcb_component_id: "pcb_component_passive",
    source_component_id: "source_component_passive",
    center: { x: 2, y: 0 },
    width: 2.85,
    height: 1.4,
    layer: "top",
    rotation: 0,
    do_not_place: false,
    obstructs_within_bounds: true,
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_parent_gnd",
    pcb_component_id: "pcb_component_parent_connector",
    source_port_id: "source_port_parent_gnd",
    x: -3,
    y: 0,
    layers: ["top"],
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_passive_signal",
    pcb_component_id: "pcb_component_passive",
    source_port_id: "source_port_passive_signal",
    x: 1.0875,
    y: 0,
    layers: ["top"],
  },
  {
    type: "pcb_port",
    pcb_port_id: "pcb_port_passive_gnd",
    pcb_component_id: "pcb_component_passive",
    source_port_id: "source_port_passive_gnd",
    x: 2.9125,
    y: 0,
    layers: ["top"],
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_parent_gnd",
    pcb_component_id: "pcb_component_parent_connector",
    pcb_port_id: "pcb_port_parent_gnd",
    layer: "top",
    shape: "rect",
    x: -3,
    y: 0,
    width: 1,
    height: 1,
    port_hints: ["GND", "1"],
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_passive_signal",
    pcb_component_id: "pcb_component_passive",
    pcb_port_id: "pcb_port_passive_signal",
    layer: "top",
    shape: "rect",
    x: 1.0875,
    y: 0,
    width: 1.025,
    height: 1.4,
    port_hints: ["1", "left"],
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_passive_gnd",
    pcb_component_id: "pcb_component_passive",
    pcb_port_id: "pcb_port_passive_gnd",
    layer: "top",
    shape: "rect",
    x: 2.9125,
    y: 0,
    width: 1.025,
    height: 1.4,
    port_hints: ["2", "right"],
  },
  {
    type: "pcb_trace",
    pcb_trace_id: "pcb_trace_passive_gnd",
    route: [
      {
        route_type: "wire",
        x: -3,
        y: 0,
        width: 0.22,
        layer: "top",
      },
      {
        route_type: "wire",
        x: 2.9125,
        y: 0,
        width: 0.22,
        layer: "top",
      },
    ],
    subcircuit_connectivity_map_key: "passive_gnd_key",
  },
] as AnyCircuitElement[]

test("subcircuit-connected passive component on GND copper pour svg snapshot", async () => {
  const svg = runSolverAndRenderToSvg(circuitJson, {
    layer: "top",
    net_name: "GND",
    pad_margin: 0.25,
    trace_margin: 0.2,
  })

  await expect(svg).toMatchSvgSnapshot(
    import.meta.path,
    "subcircuit-passive-gnd",
  )
})
